var namespacecFSPlib_1_1python__api__client_1_1swagger__client_1_1api_1_1projects__api =
[
    [ "ProjectsApi", "classcFSPlib_1_1python__api__client_1_1swagger__client_1_1api_1_1projects__api_1_1ProjectsApi.html", "classcFSPlib_1_1python__api__client_1_1swagger__client_1_1api_1_1projects__api_1_1ProjectsApi" ]
];