var namespacecFSPlib_1_1python__api__client_1_1test_1_1test__projects__api =
[
    [ "TestProjectsApi", "classcFSPlib_1_1python__api__client_1_1test_1_1test__projects__api_1_1TestProjectsApi.html", "classcFSPlib_1_1python__api__client_1_1test_1_1test__projects__api_1_1TestProjectsApi" ]
];